## codigos de proyectos
creacion de planilla

In [1]:
import importlib
import subprocess
import sys
from pathlib import Path
import pandas as pd

required_packages = {
    'pandas': 'pandas',
    'openpyxl': 'openpyxl',
    'matplotlib': 'matplotlib',
}

In [2]:
# carga planilla
codigos = Path('codigos_proyectos.xlsx')
df_codigos = pd.read_excel(codigos)

df_codigos.sample(10)

        Codigo                                             Nombre
694    2208007   ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS
438    2208007   ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS
259    2208010  SUSCRIPCION APLICACIONES DE EDICION Y TRANSCRI...
797  29.06.001          SELICO 631 - Adquisición HP Elitedesk 805
718    2208007   ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS
788  29.06.001          SELICO 646/2025 - Equipos computacionales
723    2208007   ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS
650    2208007   ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS
790  22.02.002  SELICO 622-2025 TARJETAS VESTUARIO AÑO 2026 PA...
516    2208007   ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS

In [6]:
# elimina los codigos duplicados
df_codigos = df_codigos.drop_duplicates(subset=['Codigo'], keep='first')
df_codigos.sample(10)

                  Codigo                                             Nombre
9                  22.08  Servicio del limpieza interna y externa y exte...
260              2211999  CONTRATACION SERVICIOS DE PRODUCCION DE EVENTO...
1              22.06.001  Servicio de Mantención y Reparaciones Menores ...
729              3103003   SEGURO DE DRONE - DEPTO. ASENTAMIENTOS PRECARIOS
3              22.09.006  Servicio de Arriendo de Impresoras Multifuncio...
111            22.06.007  Licitación para la Contratación del Servicio d...
326              2210002  SEGURO OBLIGATORIO ACCIDENTES PERSONALES (SOAP...
379              2905999  ADQUISICION DE HORNOS Y MICROONDAS - SECCION I...
793  22.02.002 22.08.008  SELICO 625 - TARJETAS VESTUARIO TECNICO EN PAR...
775              2907002   IMPLEMENTACIÓN CRM SIAC NUEVA PLATAFORMA - DINFO

In [8]:
# crea un nuevo excel en base a los codigos unicos
df_codigos.to_excel('codigos_unicos.xlsx', index=False)